In [107]:
import pickle
import numpy as np
# Read as binary
with open('train_qa.txt', 'rb') as fp:
    train_data = pickle.load(fp)

In [108]:
train_data

[(['Mary',
   'moved',
   'to',
   'the',
   'bathroom',
   '.',
   'Sandra',
   'journeyed',
   'to',
   'the',
   'bedroom',
   '.'],
  ['Is', 'Sandra', 'in', 'the', 'hallway', '?'],
  'no'),
 (['Mary',
   'moved',
   'to',
   'the',
   'bathroom',
   '.',
   'Sandra',
   'journeyed',
   'to',
   'the',
   'bedroom',
   '.',
   'Mary',
   'went',
   'back',
   'to',
   'the',
   'bedroom',
   '.',
   'Daniel',
   'went',
   'back',
   'to',
   'the',
   'hallway',
   '.'],
  ['Is', 'Daniel', 'in', 'the', 'bathroom', '?'],
  'no'),
 (['Mary',
   'moved',
   'to',
   'the',
   'bathroom',
   '.',
   'Sandra',
   'journeyed',
   'to',
   'the',
   'bedroom',
   '.',
   'Mary',
   'went',
   'back',
   'to',
   'the',
   'bedroom',
   '.',
   'Daniel',
   'went',
   'back',
   'to',
   'the',
   'hallway',
   '.',
   'Sandra',
   'went',
   'to',
   'the',
   'kitchen',
   '.',
   'Daniel',
   'went',
   'back',
   'to',
   'the',
   'bathroom',
   '.'],
  ['Is', 'Daniel', 'in', 'the', '

In [109]:
with open('test_qa.txt', 'rb') as fp:
    test_data = pickle.load(fp)

In [110]:
test_data

[(['Mary',
   'got',
   'the',
   'milk',
   'there',
   '.',
   'John',
   'moved',
   'to',
   'the',
   'bedroom',
   '.'],
  ['Is', 'John', 'in', 'the', 'kitchen', '?'],
  'no'),
 (['Mary',
   'got',
   'the',
   'milk',
   'there',
   '.',
   'John',
   'moved',
   'to',
   'the',
   'bedroom',
   '.',
   'Mary',
   'discarded',
   'the',
   'milk',
   '.',
   'John',
   'went',
   'to',
   'the',
   'garden',
   '.'],
  ['Is', 'John', 'in', 'the', 'kitchen', '?'],
  'no'),
 (['Mary',
   'got',
   'the',
   'milk',
   'there',
   '.',
   'John',
   'moved',
   'to',
   'the',
   'bedroom',
   '.',
   'Mary',
   'discarded',
   'the',
   'milk',
   '.',
   'John',
   'went',
   'to',
   'the',
   'garden',
   '.',
   'Daniel',
   'moved',
   'to',
   'the',
   'bedroom',
   '.',
   'Daniel',
   'went',
   'to',
   'the',
   'garden',
   '.'],
  ['Is', 'John', 'in', 'the', 'garden', '?'],
  'yes'),
 (['Mary',
   'got',
   'the',
   'milk',
   'there',
   '.',
   'John',
   'moved',


In [15]:
len(train_data)

10000

In [16]:
len(test_data)

1000

In [17]:
vocab= set()

In [18]:
all_data = train_data + test_data

In [19]:
for story,question,ans in all_data:
    vocab = vocab.union(set(story))
    vocab = vocab.union(set(question))

In [20]:
vocab.add("yes")
vocab.add("no")

In [21]:
vocab

{'.',
 '?',
 'Daniel',
 'Is',
 'John',
 'Mary',
 'Sandra',
 'apple',
 'back',
 'bathroom',
 'bedroom',
 'discarded',
 'down',
 'dropped',
 'football',
 'garden',
 'got',
 'grabbed',
 'hallway',
 'in',
 'journeyed',
 'kitchen',
 'left',
 'milk',
 'moved',
 'no',
 'office',
 'picked',
 'put',
 'the',
 'there',
 'to',
 'took',
 'travelled',
 'up',
 'went',
 'yes'}

In [22]:
len(vocab)

37

In [23]:
vocab_len = len(vocab) + 1

In [24]:
max_story_len = max([len(data[0]) for data in all_data])
max_story_len

156

In [25]:
max_ques_len = max([len(data[1]) for data in all_data])
max_ques_len

6

In [26]:
from keras.preprocessing.sequence import pad_sequences
from keras.preprocessing.text import Tokenizer

In [27]:
tokenizer = Tokenizer(filters=[])

In [28]:
tokenizer.fit_on_texts(vocab)

In [29]:
tokenizer.word_index

{'went': 1,
 'office': 2,
 'football': 3,
 'mary': 4,
 'yes': 5,
 'the': 6,
 'journeyed': 7,
 'milk': 8,
 'sandra': 9,
 'no': 10,
 'back': 11,
 'kitchen': 12,
 '.': 13,
 'travelled': 14,
 'took': 15,
 'left': 16,
 '?': 17,
 'bathroom': 18,
 'garden': 19,
 'hallway': 20,
 'got': 21,
 'in': 22,
 'discarded': 23,
 'to': 24,
 'grabbed': 25,
 'apple': 26,
 'moved': 27,
 'daniel': 28,
 'put': 29,
 'dropped': 30,
 'picked': 31,
 'bedroom': 32,
 'up': 33,
 'there': 34,
 'john': 35,
 'is': 36,
 'down': 37}

In [30]:
train_story_text = []
train_ques_text = []
train_ans = []
for story,ques,ans in train_data:
  train_story_text.append(story)
  train_ques_text.append(ques)
  train_ans.append(ans)

In [31]:
train_story_seq = tokenizer.texts_to_sequences(train_story_text)

In [32]:
train_story_seq

[[4, 27, 24, 6, 18, 13, 9, 7, 24, 6, 32, 13],
 [4,
  27,
  24,
  6,
  18,
  13,
  9,
  7,
  24,
  6,
  32,
  13,
  4,
  1,
  11,
  24,
  6,
  32,
  13,
  28,
  1,
  11,
  24,
  6,
  20,
  13],
 [4,
  27,
  24,
  6,
  18,
  13,
  9,
  7,
  24,
  6,
  32,
  13,
  4,
  1,
  11,
  24,
  6,
  32,
  13,
  28,
  1,
  11,
  24,
  6,
  20,
  13,
  9,
  1,
  24,
  6,
  12,
  13,
  28,
  1,
  11,
  24,
  6,
  18,
  13],
 [4,
  27,
  24,
  6,
  18,
  13,
  9,
  7,
  24,
  6,
  32,
  13,
  4,
  1,
  11,
  24,
  6,
  32,
  13,
  28,
  1,
  11,
  24,
  6,
  20,
  13,
  9,
  1,
  24,
  6,
  12,
  13,
  28,
  1,
  11,
  24,
  6,
  18,
  13,
  28,
  31,
  33,
  6,
  3,
  34,
  13,
  28,
  1,
  24,
  6,
  32,
  13],
 [4,
  27,
  24,
  6,
  18,
  13,
  9,
  7,
  24,
  6,
  32,
  13,
  4,
  1,
  11,
  24,
  6,
  32,
  13,
  28,
  1,
  11,
  24,
  6,
  20,
  13,
  9,
  1,
  24,
  6,
  12,
  13,
  28,
  1,
  11,
  24,
  6,
  18,
  13,
  28,
  31,
  33,
  6,
  3,
  34,
  13,
  28,
  1,
  24,
  6,
  32,
  13,


In [33]:
# Create our own list of list of word indicies with padding.
def vectorize_stories(data, word_index=tokenizer.word_index, max_story_len=max_story_len, max_question_len=max_ques_len):
    # Stories = X
    X = []

    # Questions = Xq
    Xq = []

    # Y Correct Answer ['yes', 'no']
    Y = []
    for story, query, answer in data:

        # for each story
        # [23, 14, 15]
        x = [word_index[word.lower()] for word in story]
        xq = [word_index[word.lower()] for word in query]

        y = np.zeros(len(word_index)+1)
        y[word_index[answer]] = 1

        X.append(x)   # X holds list of lists of word indices for stories.
        Xq.append(xq) # Xq holds list of lists for word indices for questions.
        Y.append(y) # Y holds lists of lists of (38) biniary numbers, only 1 of them is 1.

    return (pad_sequences(X, maxlen=max_story_len), pad_sequences(Xq, maxlen=max_question_len), np.array(Y))


In [34]:
inputs_train, queries_train, answers_train = vectorize_stories(train_data)

In [35]:
inputs_test, queries_test, answers_test = vectorize_stories(test_data)

In [36]:
inputs_test

array([[ 0,  0,  0, ...,  6, 32, 13],
       [ 0,  0,  0, ...,  6, 19, 13],
       [ 0,  0,  0, ...,  6, 19, 13],
       ...,
       [ 0,  0,  0, ...,  6, 26, 13],
       [ 0,  0,  0, ...,  6, 19, 13],
       [ 0,  0,  0, ..., 26, 34, 13]], dtype=int32)

In [37]:
answers_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [38]:
tokenizer.word_index['yes']

5

In [39]:
tokenizer.word_index['no']

10

In [40]:
sum(answers_test)

array([  0.,   0.,   0.,   0.,   0., 497.,   0.,   0.,   0.,   0., 503.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.])

In [41]:
!pip install keras
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import Input, Activation, Dense, Permute, Dropout, add, dot, concatenate, LSTM
from keras.models import Sequential, Model
from keras.layers import Embedding
from keras.layers import Input, Activation, Dense, Permute, Dropout, add, dot, concatenate, LSTM

In [42]:
# PLACEHOLDER shape=(max_story_len, batch_size)
input_sequence = Input(max_story_len,)
question = Input((max_ques_len,))

In [43]:
# vocab_len
vocab_size = len(vocab) + 1

In [44]:
# INPUT ENCODER M
input_encoder_m = Sequential()
input_encoder_m.add(Embedding(input_dim=vocab_size, output_dim=64))
input_encoder_m.add(Dropout(0.3))

# OUTPUT
# (samples, story_maxlen, embedding_dim)

In [45]:
# INPUT ENCODER C
input_encoder_c = Sequential()
input_encoder_c.add(Embedding(input_dim=vocab_size, output_dim=max_ques_len))
input_encoder_c.add(Dropout(0.3))

# OUTPUT
# (samples, story_maxlen, max_question_len)

In [46]:
question_encoder = Sequential()
question_encoder.add(Embedding(input_dim=vocab_size, output_dim=64, input_length=max_ques_len))
question_encoder.add(Dropout(0.3))

In [47]:
input_encoded_m = input_encoder_m(input_sequence)
input_encoded_c = input_encoder_c(input_sequence)
question_encoded = question_encoder(question)

In [48]:
print(input_encoded_m.shape)
print(question_encoded.shape)

(None, 156, 64)
(None, 6, 64)


In [49]:
match = dot([input_encoded_m, question_encoded], axes=(2,2)) # why axes is (2,2) ==> dot product along the embedding dim (64 numbers dot 64 numbers)
match = Activation('softmax')(match)


In [50]:
response = add([match, input_encoded_c]) # (samples, story_maxlen, query_maxlen)
response = Permute((2,1))(response) # (samples, query_maxlen, story_maxlen)


In [51]:
answer = concatenate([response, question_encoded])

In [52]:
answer

<KerasTensor: shape=(None, 6, 220) dtype=float32 (created by layer 'concatenate')>

In [53]:
answer = LSTM(32)(answer)

In [54]:
print(answer.shape)

(None, 32)


In [55]:
answer = Dropout(0.5)(answer)

In [56]:
answer = Dense(vocab_size)(answer)

In [57]:
answer = Activation('softmax')(answer)

In [58]:
answer

<KerasTensor: shape=(None, 38) dtype=float32 (created by layer 'activation_1')>

In [59]:
model = Model([input_sequence, question], answer)

In [60]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])


In [61]:
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_1 (InputLayer)        [(None, 156)]                0         []                            
                                                                                                  
 input_2 (InputLayer)        [(None, 6)]                  0         []                            
                                                                                                  
 sequential (Sequential)     (None, None, 64)             2432      ['input_1[0][0]']             
                                                                                                  
 sequential_2 (Sequential)   (None, 6, 64)                2432      ['input_2[0][0]']             
                                                                                              

In [62]:
history = model.fit([inputs_train, queries_train], answers_train, batch_size=32, epochs=100, validation_data=([inputs_test, queries_test],
                                                                                                              answers_test))

Epoch 1/100
313/313 [==============================] - 6s 11ms/step - loss: 0.9947 - accuracy: 0.4975 - val_loss: 0.7001 - val_accuracy: 0.5030
Epoch 2/100
313/313 [==============================] - 3s 10ms/step - loss: 0.7224 - accuracy: 0.5027 - val_loss: 0.7010 - val_accuracy: 0.5030
Epoch 3/100
313/313 [==============================] - 3s 8ms/step - loss: 0.7054 - accuracy: 0.4943 - val_loss: 0.6944 - val_accuracy: 0.5030
Epoch 4/100
313/313 [==============================] - 3s 10ms/step - loss: 0.6991 - accuracy: 0.5020 - val_loss: 0.6942 - val_accuracy: 0.4970
Epoch 5/100
313/313 [==============================] - 3s 9ms/step - loss: 0.6987 - accuracy: 0.4934 - val_loss: 0.6942 - val_accuracy: 0.4970
Epoch 6/100
313/313 [==============================] - 3s 8ms/step - loss: 0.6972 - accuracy: 0.4973 - val_loss: 0.6934 - val_accuracy: 0.5030
Epoch 7/100
313/313 [==============================] - 3s 8ms/step - loss: 0.6962 - accuracy: 0.5026 - val_loss: 0.6933 - val_accuracy: 0.5

dict_keys(['loss', 'accuracy', 'val_loss', 'val_accuracy'])


NameError: name 'history_dict' is not defined

In [67]:
model.save('mybrandnewmodel.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [68]:
pred_result = model.predict(([inputs_test, queries_test]))

32/32 [==============================] - 0s 2ms/step


In [69]:
pred_result.shape

(1000, 38)

In [70]:
pred_result[0]

array([4.7341620e-14, 5.5154374e-14, 6.5673317e-14, 6.3207191e-14,
       4.8779140e-14, 7.0323225e-04, 7.1692692e-14, 6.7509949e-14,
       5.5979455e-14, 7.5803933e-14, 9.9929684e-01, 5.4843550e-14,
       6.5504683e-14, 6.3218636e-14, 6.4978317e-14, 6.1121511e-14,
       5.0247279e-14, 7.2035233e-14, 7.1529608e-14, 5.5360213e-14,
       6.1000277e-14, 8.8824137e-14, 7.1626400e-14, 6.7301409e-14,
       8.3167197e-14, 6.1720858e-14, 7.1536161e-14, 6.4308930e-14,
       9.6606744e-14, 5.5525388e-14, 5.7318882e-14, 6.5717180e-14,
       5.8084539e-14, 5.6802253e-14, 9.2385924e-14, 4.5996440e-14,
       7.9662459e-14, 7.4368531e-14], dtype=float32)

In [71]:
index_word = {index: word for word, index in tokenizer.word_index.items()}

In [72]:
predictions = np.argmax(pred_result, axis=1)
pred_answers = [index_word[pred] for pred in predictions]
pred_answers

['no',
 'no',
 'yes',
 'yes',
 'no',
 'no',
 'no',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'no',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'no',
 'yes',
 'no',
 'yes',
 'no',
 'no',
 'yes',
 'yes',
 'no',
 'no',
 'yes',
 'yes',
 'no',
 'no',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'no',
 'no',
 'no',
 'yes',
 'yes',
 'yes',
 'no',
 'no',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'no',
 'no',
 'yes',
 'no',
 'yes',
 'no',
 'no',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'no',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'no',
 'no',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'no',
 'no',
 'no',
 'no',
 'yes',
 'no',
 'yes',
 'yes',
 'no',
 'no',
 'no',
 'yes',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'yes',
 'no',
 'no',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'no',
 'yes',
 'yes',
 'no',
 'yes',
 'no',
 'no',
 'no',
 'no',
 'yes',
 'no',
 '

In [96]:
my_story = "John left the kitchen . Sandra dropped the football in the garden ."

In [97]:
my_story.split()

['John',
 'left',
 'the',
 'kitchen',
 '.',
 'Sandra',
 'dropped',
 'the',
 'football',
 'in',
 'the',
 'garden',
 '.']

In [98]:
my_question = "Is the football in the garden ?"

In [99]:
my_question.split()

['Is', 'the', 'football', 'in', 'the', 'garden', '?']

In [100]:
mydata = [(my_story.split(), my_question.split(), 'yes')]

In [101]:
my_story, my_ques, my_ans = vectorize_stories(mydata)

In [102]:
pred_result = model.predict([my_story, my_ques])

1/1 [==============================] - 0s 16ms/step


In [103]:
val_max = np.argmax(pred_result[0])

In [104]:
# Get the answer corresponding to the highest predict probabilty.
for key, val in tokenizer.word_index.items():
    if val == val_max:
        k = key

In [105]:
k

'yes'

In [106]:
# Find out what's the highest predict probability.
pred_result[0][val_max]

0.90725887